//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Objective.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Choice> Choice { get; set; }
        public virtual DbSet<ExamBody> ExamBody { get; set; }
        public virtual DbSet<ExamTopic> ExamTopic { get; set; }
        public virtual DbSet<GetExam> GetExam { get; set; }
        public virtual DbSet<IOC> IOCs { get; set; }
        public virtual DbSet<Lesson> Lesson { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Objective> Objective { get; set; }
        public virtual DbSet<Participant> Participant { get; set; }
        public virtual DbSet<Proposition> Proposition { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagram { get; set; }
        public virtual DbSet<TestGroup> TestGroup { get; set; }
        public virtual DbSet<Testing> Testing { get; set; }
        public virtual DbSet<UserSystem> UserSystem { get; set; }
    }
}
