//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Objective.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamBody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamBody()
        {
            this.GetExam = new HashSet<GetExam>();
        }
    
        public int ExamBodyID { get; set; }
        public int ExamtopicID { get; set; }
        public Nullable<double> KR20 { get; set; }
        public Nullable<double> KR21 { get; set; }
    
        public virtual ExamTopic ExamTopic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GetExam> GetExam { get; set; }
    }
}
