//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Objective.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public string ParticipantID { get; set; }
        public string UserID { get; set; }
        public string SubjectID { get; set; }
        public string Status { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual UserSystem UserSystem { get; set; }
    }
}
