//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Objective.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testing
    {
        public int ExamBodyID { get; set; }
        public int ProposID { get; set; }
        public string UserID { get; set; }
        public string AnswerStudent { get; set; }
        public Nullable<int> NumberOfTimes { get; set; }
    
        public virtual GetExam GetExam { get; set; }
        public virtual UserSystem UserSystem { get; set; }
    }
}
